---
sidebar: sidebar 
permalink: reference-permissions-aws.html 
keywords: permissions, actions, aws, aws permissions 
summary: Cloud ManagerでAWSでコネクタインスタンスを起動するときに、そのAWSアカウント内のリソースとプロセスを管理するための権限を提供するポリシーがインスタンスに関連付けられます。Connectorでは、権限を使用してAPI呼び出しを実行することで、EC2、S3、CloudFormation、IAM、 キー管理サービスなど。 
---
= Connector の AWS 権限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud ManagerでAWSでコネクタインスタンスを起動するときに、そのAWSアカウント内のリソースとプロセスを管理するための権限を提供するポリシーがインスタンスに関連付けられます。Connectorでは、権限を使用してAPI呼び出しを実行することで、EC2、S3、CloudFormation、IAM、 Key Management Service（KMS；キー管理サービス）など。



== IAMポリシー

以下のIAMポリシーは、ConnectorがAWSリージョンに基づいてパブリッククラウド環境内のリソースとプロセスを管理するために必要な権限を提供します。

Cloud Managerからコネクタを直接作成すると、Cloud Managerはこのポリシーをコネクタに自動的に適用します。

AWS MarketplaceからConnectorを導入する場合や、LinuxホストにConnectorを手動でインストールする場合は、手動でポリシーを設定する必要があります。

また、新しい権限が以降のリリースで追加されるときに、ポリシーが最新の状態であることを確認する必要があります。

[role="tabbed-block"]
====
.標準領域
--
[source, json]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "cvoServicePolicy",
      "Effect": "Allow",
      "Action": [
        "ec2:DescribeInstances",
        "ec2:DescribeInstanceStatus",
        "ec2:RunInstances",
        "ec2:ModifyInstanceAttribute",
        "ec2:DescribeInstanceAttribute",
        "ec2:DescribeRouteTables",
        "ec2:DescribeImages",
        "ec2:CreateTags",
        "ec2:CreateVolume",
        "ec2:DescribeVolumes",
        "ec2:ModifyVolumeAttribute",
        "ec2:CreateSecurityGroup",
        "ec2:DescribeSecurityGroups",
        "ec2:RevokeSecurityGroupEgress",
        "ec2:AuthorizeSecurityGroupEgress",
        "ec2:AuthorizeSecurityGroupIngress",
        "ec2:RevokeSecurityGroupIngress",
        "ec2:CreateNetworkInterface",
        "ec2:DescribeNetworkInterfaces",
        "ec2:ModifyNetworkInterfaceAttribute",
        "ec2:DescribeSubnets",
        "ec2:DescribeVpcs",
        "ec2:DescribeDhcpOptions",
        "ec2:CreateSnapshot",
        "ec2:DescribeSnapshots",
        "ec2:GetConsoleOutput",
        "ec2:DescribeKeyPairs",
        "ec2:DescribeRegions",
        "ec2:DescribeTags",
        "cloudformation:CreateStack",
        "cloudformation:DescribeStacks",
        "cloudformation:DescribeStackEvents",
        "cloudformation:ValidateTemplate",
        "iam:PassRole",
        "iam:CreateRole",
        "iam:PutRolePolicy",
        "iam:CreateInstanceProfile",
        "iam:AddRoleToInstanceProfile",
        "iam:RemoveRoleFromInstanceProfile",
        "iam:ListInstanceProfiles",
        "sts:DecodeAuthorizationMessage",
        "ec2:AssociateIamInstanceProfile",
        "ec2:DescribeIamInstanceProfileAssociations",
        "ec2:DisassociateIamInstanceProfile",
        "s3:GetBucketTagging",
        "s3:GetBucketLocation",
        "s3:ListBucket",
        "s3:CreateBucket",
        "s3:GetLifecycleConfiguration",
        "s3:ListBucketVersions",
        "s3:GetBucketPolicyStatus",
        "s3:GetBucketPublicAccessBlock",
        "s3:GetBucketPolicy",
        "s3:GetBucketAcl",
        "kms:List*",
        "kms:ReEncrypt*",
        "kms:Describe*",
        "kms:CreateGrant",
        "ce:GetReservationUtilization",
        "ce:GetDimensionValues",
        "ce:GetCostAndUsage",
        "ce:GetTags",
        "ec2:CreatePlacementGroup",
        "ec2:DescribeReservedInstancesOfferings",
        "sts:AssumeRole",
        "ec2:AssignPrivateIpAddresses",
        "ec2:CreateRoute",
        "ec2:DescribeVpcs",
        "ec2:ReplaceRoute",
        "ec2:UnassignPrivateIpAddresses",
        "s3:PutObjectTagging",
        "s3:GetObjectTagging",
        "fsx:Describe*",
        "fsx:List*",
        "ec2:DeleteSecurityGroup",
        "ec2:DeleteNetworkInterface",
        "ec2:DeleteSnapshot",
        "ec2:DeleteTags",
        "ec2:DeleteRoute",
        "ec2:DeletePlacementGroup",
        "iam:DeleteRole",
        "iam:DeleteRolePolicy",
        "iam:DeleteInstanceProfile",
        "cloudformation:DeleteStack",
        "ec2:DescribePlacementGroups",
        "iam:GetRolePolicy",
		"s3:ListAllMyBuckets",
        "s3:GetObject",
        "iam:GetRole",
        "s3:DeleteObject",
        "s3:DeleteObjectVersion",
        "s3:PutObject",
		"ec2:ModifyVolume",
        "ec2:DescribeVolumesModifications"
      ],
      "Resource": "*"
    },
    {
      "Sid": "backupPolicy",
      "Effect": "Allow",
      "Action": [
        "ec2:StartInstances",
        "ec2:StopInstances",
        "ec2:DescribeInstances",
        "ec2:DescribeInstanceStatus",
        "ec2:RunInstances",
        "ec2:TerminateInstances",
        "ec2:DescribeInstanceAttribute",
        "ec2:DescribeImages",
        "ec2:CreateTags",
        "ec2:CreateVolume",
        "ec2:CreateSecurityGroup",
        "ec2:DescribeSubnets",
        "ec2:DescribeVpcs",
        "ec2:DescribeRegions",
        "cloudformation:CreateStack",
        "cloudformation:DeleteStack",
        "cloudformation:DescribeStacks",
        "kms:List*",
        "kms:Describe*",
        "ec2:describeVpcEndpoints",
        "kms:ListAliases",
        "athena:StartQueryExecution",
        "athena:GetQueryResults",
        "athena:GetQueryExecution",
        "athena:StopQueryExecution",
        "glue:CreateDatabase",
        "glue:CreateTable",
        "glue:BatchDeletePartition"
      ],
      "Resource": "*"
    },
    {
      "Sid": "backupS3Policy",
      "Effect": "Allow",
      "Action": [
        "s3:GetBucketLocation",
        "s3:ListAllMyBuckets",
        "s3:ListBucket",
        "s3:CreateBucket",
        "s3:GetLifecycleConfiguration",
        "s3:PutLifecycleConfiguration",
        "s3:PutBucketTagging",
        "s3:ListBucketVersions",
        "s3:GetBucketAcl",
        "s3:PutBucketPublicAccessBlock",
        "s3:GetObject",
        "s3:PutEncryptionConfiguration",
        "s3:DeleteObject",
        "s3:DeleteObjectVersion",
        "s3:ListBucketMultipartUploads",
        "s3:PutObject",
        "s3:PutBucketAcl",
        "s3:AbortMultipartUpload",
        "s3:ListMultipartUploadParts",
        "s3:DeleteBucket"
      ],
      "Resource": [
        "arn:aws:s3:::netapp-backup-*"
      ]
    },
    {
      "Sid": "tagServicePolicy",
      "Effect": "Allow",
      "Action": [
        "ec2:CreateTags",
        "ec2:DeleteTags",
        "ec2:DescribeTags",
        "tag:getResources",
        "tag:getTagKeys",
        "tag:getTagValues",
        "tag:TagResources",
        "tag:UntagResources"
      ],
      "Resource": "*"
    },
    {
      "Sid": "fabricPoolS3Policy",
      "Effect": "Allow",
      "Action": [
        "s3:CreateBucket",
        "s3:GetLifecycleConfiguration",
        "s3:PutLifecycleConfiguration",
        "s3:PutBucketTagging",
        "s3:ListBucketVersions",
        "s3:GetBucketPolicyStatus",
        "s3:GetBucketPublicAccessBlock",
        "s3:GetBucketAcl",
        "s3:GetBucketPolicy",
        "s3:PutBucketPublicAccessBlock",
        "s3:DeleteBucket"
      ],
      "Resource": [
        "arn:aws:s3:::fabric-pool*"
      ]
    },
    {
      "Sid": "fabricPoolPolicy",
      "Effect": "Allow",
      "Action": [
        "ec2:DescribeRegions"
      ],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "ec2:StartInstances",
        "ec2:StopInstances",
        "ec2:TerminateInstances"
      ],
      "Condition": {
        "StringLike": {
          "ec2:ResourceTag/netapp-adc-manager": "*"
        }
      },
      "Resource": [
        "arn:aws:ec2:*:*:instance/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "ec2:StartInstances",
        "ec2:TerminateInstances",
        "ec2:AttachVolume",
        "ec2:DetachVolume"
      ],
      "Condition": {
        "StringLike": {
          "ec2:ResourceTag/GFCInstance": "*"
        }
      },
      "Resource": [
        "arn:aws:ec2:*:*:instance/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "ec2:StartInstances",
        "ec2:TerminateInstances",
        "ec2:AttachVolume",
        "ec2:DetachVolume",
        "ec2:StopInstances",
        "ec2:DeleteVolume"
      ],
      "Condition": {
        "StringLike": {
          "ec2:ResourceTag/WorkingEnvironment": "*"
        }
      },
      "Resource": [
        "arn:aws:ec2:*:*:instance/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "ec2:AttachVolume",
        "ec2:DetachVolume"
      ],
      "Resource": [
        "arn:aws:ec2:*:*:volume/*"
      ]
    },
	{
      "Effect": "Allow",
      "Action": [
        "ec2:DeleteVolume"
      ],
	  "Condition": {
        "StringLike": {
          "ec2:ResourceTag/WorkingEnvironment": "*"
        }
      },
      "Resource": [
        "arn:aws:ec2:*:*:volume/*"
      ]
    },
    {
      "Sid": "K8sServicePolicy",
      "Effect": "Allow",
      "Action": [
        "ec2:DescribeRegions",
        "iam:ListInstanceProfiles",
        "eks:ListClusters",
        "eks:DescribeCluster"
      ],
      "Resource": "*"
    },
    {
      "Sid": "GFCservicePolicy",
      "Effect": "Allow",
      "Action": [
        "cloudformation:DescribeStacks",
        "cloudwatch:GetMetricStatistics",
        "cloudformation:ListStacks"
      ],
      "Resource": "*"
    }
  ]
}
----
--
.GovCloud（US）リージョン
--
[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:ListInstanceProfiles",
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:PutRolePolicy",
                "iam:CreateInstanceProfile",
                "iam:DeleteRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:DeleteInstanceProfile",
                "ec2:ModifyVolumeAttribute",
                "sts:DecodeAuthorizationMessage",
                "ec2:DescribeImages",
                "ec2:DescribeRouteTables",
                "ec2:DescribeInstances",
                "iam:PassRole",
                "ec2:DescribeInstanceStatus",
                "ec2:RunInstances",
                "ec2:ModifyInstanceAttribute",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:DescribeVolumes",
                "ec2:DeleteVolume",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeSecurityGroups",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "ec2:DescribeDhcpOptions",
                "ec2:CreateSnapshot",
                "ec2:DeleteSnapshot",
                "ec2:DescribeSnapshots",
                "ec2:StopInstances",
                "ec2:GetConsoleOutput",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeRegions",
                "ec2:DeleteTags",
                "ec2:DescribeTags",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:ValidateTemplate",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets",
                "s3:GetBucketTagging",
                "s3:GetBucketLocation",
                "s3:CreateBucket",
                "s3:GetBucketPolicyStatus",
                "s3:GetBucketPublicAccessBlock",
                "s3:GetBucketAcl",
                "s3:GetBucketPolicy",
                "kms:List*",
                "kms:ReEncrypt*",
                "kms:Describe*",
                "kms:CreateGrant",
                "ec2:AssociateIamInstanceProfile",
                "ec2:DescribeIamInstanceProfileAssociations",
                "ec2:DisassociateIamInstanceProfile",
                "ec2:DescribeInstanceAttribute",
                "ce:GetReservationUtilization",
                "ce:GetDimensionValues",
                "ce:GetCostAndUsage",
                "ce:GetTags",
                "ec2:CreatePlacementGroup",
                "ec2:DeletePlacementGroup"
            ],
            "Resource": "*"
        },
        {
            "Sid": "fabricPoolPolicy",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteBucket",
                "s3:GetLifecycleConfiguration",
                "s3:PutLifecycleConfiguration",
                "s3:PutBucketTagging",
                "s3:ListBucketVersions",
                "s3:GetBucketPolicyStatus",
                "s3:GetBucketPublicAccessBlock",
                "s3:GetBucketAcl",
                "s3:GetBucketPolicy",
                "s3:PutBucketPublicAccessBlock"
            ],
            "Resource": [
                "arn:aws-us-gov:s3:::fabric-pool*"
            ]
        },
        {
            "Sid": "backupPolicy",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteBucket",
                "s3:GetLifecycleConfiguration",
                "s3:PutLifecycleConfiguration",
                "s3:PutBucketTagging",
                "s3:ListBucketVersions",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets",
                "s3:GetBucketTagging",
                "s3:GetBucketLocation",
                "s3:GetBucketPolicyStatus",
                "s3:GetBucketPublicAccessBlock",
                "s3:GetBucketAcl",
                "s3:GetBucketPolicy",
                "s3:PutBucketPublicAccessBlock"
            ],
            "Resource": [
                "arn:aws-us-gov:s3:::netapp-backup-*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:StartInstances",
                "ec2:TerminateInstances",
                "ec2:AttachVolume",
                "ec2:DetachVolume"
            ],
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/WorkingEnvironment": "*"
                }
            },
            "Resource": [
                "arn:aws-us-gov:ec2:*:*:instance/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:AttachVolume",
                "ec2:DetachVolume"
            ],
            "Resource": [
                "arn:aws-us-gov:ec2:*:*:volume/*"
            ]
        }
    ]
}
----
--
.C2S環境
--
[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [{
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceStatus",
                "ec2:RunInstances",
                "ec2:ModifyInstanceAttribute",
                "ec2:DescribeRouteTables",
                "ec2:DescribeImages",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:DescribeVolumes",
                "ec2:ModifyVolumeAttribute",
                "ec2:DeleteVolume",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeSecurityGroups",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "ec2:DescribeDhcpOptions",
                "ec2:CreateSnapshot",
                "ec2:DeleteSnapshot",
                "ec2:DescribeSnapshots",
                "ec2:GetConsoleOutput",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeRegions",
                "ec2:DeleteTags",
                "ec2:DescribeTags",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:ValidateTemplate",
                "iam:PassRole",
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:PutRolePolicy",
                "iam:CreateInstanceProfile",
                "iam:DeleteRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:DeleteInstanceProfile",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:GetBucketTagging",
                "s3:GetBucketLocation",
                "s3:ListAllMyBuckets",
                "kms:List*",
                "kms:Describe*",
                "ec2:AssociateIamInstanceProfile",
                "ec2:DescribeIamInstanceProfileAssociations",
                "ec2:DisassociateIamInstanceProfile",
                "ec2:DescribeInstanceAttribute",
                "ec2:CreatePlacementGroup",
                "ec2:DeletePlacementGroup",
                "iam:ListinstanceProfiles"
            ],
            "Resource": "*"
        },
        {
            "Sid": "fabricPoolPolicy",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteBucket",
                "s3:GetLifecycleConfiguration",
                "s3:PutLifecycleConfiguration",
                "s3:PutBucketTagging",
                "s3:ListBucketVersions"
            ],
            "Resource": [
                "arn:aws-iso:s3:::fabric-pool*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:StartInstances",
                "ec2:StopInstances",
                "ec2:TerminateInstances",
                "ec2:AttachVolume",
                "ec2:DetachVolume"
            ],
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/WorkingEnvironment": "*"
                }
            },
            "Resource": [
                "arn:aws-iso:ec2:*:*:instance/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:AttachVolume",
                "ec2:DetachVolume"
            ],
            "Resource": [
                "arn:aws-iso:ec2:*:*:volume/*"
            ]
        }
    ]
}
----
--
====


== AWS権限の使用方法

以降のセクションでは、各ネットアップクラウドサービスに対する権限の使用方法について説明します。この情報は、企業のポリシーによって、必要な場合にのみアクセス許可が指定されるように指定されている場合に役立ちます。



=== AppTemplateタグ

AppTemplate Taggingサービスを使用する場合、Connectorは次のAPI要求を実行してAWSリソースのタグを管理します。

* ec2：CreateTags
* EC2:タグを削除します
* EC2: DescribeTags (説明タグ)
* Tag:getResources
* tag:getTagKeys
* tag:getTagValues
* Tag:タグリソース
* タグ: UntagResources




=== クラウドバックアップ

コネクタは、Cloud Backupのリストアインスタンスを導入するために次のAPI要求を実行します。

* EC2：StartInstances（EC2：開始インスタンス
* EC2：StopInstances
* EC2: DescribeInstances
* EC2: DescribeInstanceStatus
* EC2：RunInstances
* EC2：TerminateInstances
* EC2: DescribeInstanceAttributeのこと
* EC2: DescribeImages
* ec2：CreateTags
* EC2：CreateVolume
* EC2：CreateSecurityGroup
* EC2: DescribeSubnets
* EC2: DescribeVpcs
* EC2: DescribeRegions (説明領域
* CloudFormation：CreateStack
* CloudFormation：DeleteStack
* CloudFormation：DescribeStack


Connectorは、Amazon S3でバックアップを管理するために次のAPI要求を実行します。

* S3 ： GetBucketLocation
* S3 ： ListAllMyBuckets
* S3 ： ListBucket
* S3 ： CreateBucket を指定します
* S3 ： GetLifecycleConfiguration
* S3 ： PutLifecycleConfiguration
* S3 ： PutBucketTagging
* S3 ： ListBucketVersions
* S3 ： GetBucketAcl
* S3：PutBucketPublicAccessBlock
* KMS：リスト*
* KMS：説明*
* S3 ： GetObject
* ec2c:ディスクエンドポイントの説明
* KMS：エイリアスを確認する
* S3 ： PutEncryptionConfiguration


コネクタは、Search & Restoreメソッドを使用してボリュームとファイルをリストアする場合に次のAPI要求を実行します。

* S3 ： CreateBucket を指定します
* S3 ： DeleteObject
* S3 ： DeleteObjectVersion
* S3 ： GetBucketAcl
* S3 ： ListBucket
* S3 ： ListBucketVersions
* S3 ： ListBucketMultipartUploads
* S3 ： PutObject
* S3：PutBucketAcl
* S3 ： PutLifecycleConfiguration
* S3：PutBucketPublicAccessBlock
* S3 ： AbortMultipartUpload
* S3 ： ListMultipartUploadParts
* Athena：StartQueryExecutionc
* Athena: GetQueryResults.
* Athena: GetQueryExecution
* Athena：StopQueryExecution
* グルー：データベースを作成します
* グルー: CreateTable
* グルー: BatchDeletePartition




=== クラウドデータの意味

Connectorは、Cloud Data Senseインスタンスを導入するために次のAPI要求を実行します。

* EC2: DescribeInstances
* EC2: DescribeInstanceStatus
* EC2：RunInstances
* EC2：TerminateInstances
* ec2：CreateTags
* EC2：CreateVolume
* EC2：AttachVolume
* EC2：CreateSecurityGroup
* EC2: DeleteSecurityGroup
* EC2: DescribeSecurityGroups
* EC2：CreateNetworkInterface
* EC2: DescribeNetworkInterfaces
* EC2：DeleteNetworkInterface
* EC2: DescribeSubnets
* EC2: DescribeVpcs
* EC2: CreateSnapshotの作成
* EC2: DescribeRegions (説明領域
* CloudFormation：CreateStack
* CloudFormation：DeleteStack
* CloudFormation：DescribeStack
* CloudFormation：DescribeStackEvents
* IAM：AddRoleToInstanceProfile
* EC2: AssociateIamInstanceProfile
* EC2: DescribeIamInstanceProfileAssociations


Cloud Data Senseを使用している場合、コネクタはS3バケットのスキャンを行うために次のAPI要求を実行します。

* IAM：AddRoleToInstanceProfile
* EC2: AssociateIamInstanceProfile
* EC2: DescribeIamInstanceProfileAssociations
* S3 ： GetBucketTagging
* S3 ： GetBucketLocation
* S3 ： ListAllMyBuckets
* S3 ： ListBucket
* S3：GetBucketPolicyStatus
* S3 ： GetBucketPolicy
* S3 ： GetBucketAcl
* S3 ： GetObject
* IAM：GetRole
* S3 ： DeleteObject
* S3 ： DeleteObjectVersion
* S3 ： PutObject
* STS: AssumeRole




=== クラウド階層化

Cloud Tieringを使用すると、ConnectorはAmazon S3へのデータの階層化を求める次のAPI要求を実行します。

[cols="3*"]
|===
| アクション | セットアップに使用？ | 日々の業務に使用されるか？ 


| S3 ： CreateBucket を指定します | はい。 | いいえ 


| S3 ： PutLifecycleConfiguration | はい。 | いいえ 


| S3 ： GetLifecycleConfiguration | はい。 | はい。 


| EC2: DescribeRegions (説明領域 | はい。 | はい。 
|===


=== Cloud Volumes ONTAP

Connectorは、AWSでのCloud Volumes ONTAP の導入と管理に対して次のAPI要求を実行します。

[cols="5*"]
|===
| 目的 | アクション | 導入に使用 | 日々の業務に使用されるか？ | 削除しますか？ 


.13+| Cloud Volumes ONTAP インスタンスのIAMロールとインスタンスプロファイルを作成および管理します | IAM：ListInstanceProfiles | はい。 | はい。 | いいえ 


| IAM：CREATEROLE | はい。 | いいえ | いいえ 


| IAM：DeleteRole | いいえ | はい。 | はい。 


| IAM：PutRolePolicy | はい。 | いいえ | いいえ 


| IAM：CreateInstanceProfile | はい。 | いいえ | いいえ 


| IAM：DeleteRolePolicy | いいえ | はい。 | はい。 


| IAM：AddRoleToInstanceProfile | はい。 | いいえ | いいえ 


| IAM：RemoveRoleFromInstanceProfile | いいえ | はい。 | はい。 


| IAM：DeleteInstanceProfile | いいえ | はい。 | はい。 


| IAM：PassRole | はい。 | いいえ | いいえ 


| EC2: AssociateIamInstanceProfile | はい。 | はい。 | いいえ 


| EC2: DescribeIamInstanceProfileAssociations | はい。 | はい。 | いいえ 


| EC2: DisassociateIamInstanceProfile | いいえ | はい。 | いいえ 


| 読み取り許可ステータスメッセージ | STS: DecodeAuthorizationMessage | はい。 | はい。 | いいえ 


| アカウントで使用可能な指定イメージ（AMIS）について説明します | EC2: DescribeImages | はい。 | はい。 | いいえ 


| VPC内のルーティングテーブルの説明（HAペアの場合のみ必要） | EC2: DescribeRouteTables | はい。 | いいえ | いいえ 


.7+| インスタンスの停止、開始、監視 | EC2：StartInstances（EC2：開始インスタンス | はい。 | はい。 | いいえ 


| EC2：StopInstances | はい。 | はい。 | いいえ 


| EC2: DescribeInstances | はい。 | はい。 | いいえ 


| EC2: DescribeInstanceStatus | はい。 | はい。 | いいえ 


| EC2：RunInstances | はい。 | いいえ | いいえ 


| EC2：TerminateInstances | いいえ | いいえ | はい。 


| EC2：ModifyInstanceAttribute | いいえ | はい。 | いいえ 


| サポートされるインスタンスタイプに対して拡張ネットワークが有効になっていることを確認します | EC2: DescribeInstanceAttributeのこと | いいえ | はい。 | いいえ 


| メンテナンスとコストの割り当てに使用する「WorkingEnvironment」タグと「WorkingEnvironmentId」タグを使用してリソースにタグを付けます | ec2：CreateTags | はい。 | はい。 | いいえ 


.6+| Cloud Volumes ONTAP がバックエンドストレージとして使用するEBSボリュームを管理します | EC2：CreateVolume | はい。 | はい。 | いいえ 


| EC2: DescribeVolumesの場合 | はい。 | はい。 | はい。 


| EC2：ModifyVolumeAttributeのことです | いいえ | はい。 | はい。 


| EC2：AttachVolume | はい。 | はい。 | いいえ 


| EC2：DeleteVolume | いいえ | はい。 | はい。 


| EC2：DetachVolumeの場合 | いいえ | はい。 | はい。 


.7+| Cloud Volumes ONTAP のセキュリティグループを作成および管理します | EC2：CreateSecurityGroup | はい。 | いいえ | いいえ 


| EC2: DeleteSecurityGroup | いいえ | はい。 | はい。 


| EC2: DescribeSecurityGroups | はい。 | はい。 | はい。 


| EC2: RevokeSecurityGroupEgress | はい。 | いいえ | いいえ 


| ec2：AuthorizeSecurityGroupEgress | はい。 | いいえ | いいえ 


| ec2：AuthorizeSecurityGroupIngress | はい。 | いいえ | いいえ 


| EC2: RevokeSecurityGroupIngress | はい。 | はい。 | いいえ 


.4+| ターゲットサブネットのCloud Volumes ONTAP のネットワークインターフェイスを作成および管理します | EC2：CreateNetworkInterface | はい。 | いいえ | いいえ 


| EC2: DescribeNetworkInterfaces | はい。 | はい。 | いいえ 


| EC2：DeleteNetworkInterface | いいえ | はい。 | はい。 


| EC2:ModifyNetworkInterfaceAttributeのいずれかです | いいえ | はい。 | いいえ 


.2+| デスティネーションのサブネットとセキュリティグループの一覧を取得します | EC2: DescribeSubnets | はい。 | はい。 | いいえ 


| EC2: DescribeVpcs | はい。 | はい。 | いいえ 


| Cloud Volumes ONTAP インスタンスのDNSサーバおよびデフォルトのドメイン名を取得します | EC2: DescribeDhcpOptions | はい。 | いいえ | いいえ 


.3+| Cloud Volumes ONTAP 用のEBSボリュームのSnapshotを作成します | EC2: CreateSnapshotの作成 | はい。 | はい。 | いいえ 


| EC2：DeleteSnapshot | いいえ | はい。 | はい。 


| ec2: DescribeSnapshots | いいえ | はい。 | いいえ 


| AutoSupport メッセージに添付されているCloud Volumes ONTAP コンソールをキャプチャします | EC2: GetConsoleOutput | はい。 | はい。 | いいえ 


| 使用可能なキーペアのリストを取得します | EC2：DescribeKeyPairs | はい。 | いいえ | いいえ 


| 使用可能なAWSリージョンのリストを取得します | EC2: DescribeRegions (説明領域 | はい。 | はい。 | いいえ 


.2+| Cloud Volumes ONTAP インスタンスに関連付けられたリソースのタグを管理します | EC2:タグを削除します | いいえ | はい。 | はい。 


| EC2: DescribeTags (説明タグ) | いいえ | はい。 | いいえ 


.5+| AWS CloudFormationテンプレートのスタックの作成と管理 | CloudFormation：CreateStack | はい。 | いいえ | いいえ 


| CloudFormation：DeleteStack | はい。 | いいえ | いいえ 


| CloudFormation：DescribeStack | はい。 | はい。 | いいえ 


| CloudFormation：DescribeStackEvents | はい。 | いいえ | いいえ 


| CloudFormation：ValidateTemplate | はい。 | いいえ | いいえ 


.15+| Cloud Volumes ONTAP システムでデータ階層として使用するS3バケットを作成および管理します | S3 ： CreateBucket を指定します | はい。 | はい。 | いいえ 


| S3 ： DeleteBucket | いいえ | はい。 | はい。 


| S3 ： GetLifecycleConfiguration | いいえ | はい。 | いいえ 


| S3 ： PutLifecycleConfiguration | いいえ | はい。 | いいえ 


| S3 ： PutBucketTagging | いいえ | はい。 | いいえ 


| S3 ： ListBucketVersions | いいえ | はい。 | いいえ 


| S3：GetBucketPolicyStatus | いいえ | はい。 | いいえ 


| S3：GetBucketPublicAccessBlock | いいえ | はい。 | いいえ 


| S3 ： GetBucketAcl | いいえ | はい。 | いいえ 


| S3 ： GetBucketPolicy | いいえ | はい。 | いいえ 


| S3：PutBucketPublicAccessBlock | いいえ | はい。 | いいえ 


| S3 ： GetBucketTagging | いいえ | はい。 | いいえ 


| S3 ： GetBucketLocation | いいえ | はい。 | いいえ 


| S3 ： ListAllMyBuckets | いいえ | いいえ | いいえ 


| S3 ： ListBucket | いいえ | はい。 | いいえ 


.4+| AWS Key Management Service（KMS；キー管理サービス）を使用してCloud Volumes ONTAP のデータ暗号化を有効にする | KMS：リスト* | はい。 | はい。 | いいえ 


| KMS：再暗号化* | はい。 | いいえ | いいえ 


| KMS：説明* | はい。 | はい。 | いいえ 


| KMS：CreateGrant | はい。 | はい。 | いいえ 


.4+| AWSからCloud Volumes ONTAP のコストデータを取得 | CE：GetReservationUtilization | いいえ | はい。 | いいえ 


| CE：GetDimensionValues | いいえ | はい。 | いいえ 


| CE：GetCostAndUsage | いいえ | はい。 | いいえ 


| CE: GetTags. | いいえ | はい。 | いいえ 


.2+| 2つのHAノードとメディエーター用のAWS分散配置グループを1つのAWSアベイラビリティゾーンに作成して管理します | EC2：CreatePlacementGroup | はい。 | いいえ | いいえ 


| EC2: DeletePlacementGroup | いいえ | はい。 | はい。 


.2+| レポートを作成します | FSx：説明* | いいえ | はい。 | いいえ 


| FSx：リスト* | いいえ | はい。 | いいえ 


.2+| Amazon EBS Elastic Volumes機能をサポートするアグリゲートを作成して管理します | EC2: DescribeVolumesModifications ( EC2 : DescribeVolumesMod | いいえ | はい。 | いいえ 


| EC2：ModifyVolume | いいえ | はい。 | いいえ 
|===


=== グローバルファイルキャッシュ

このコネクタは、導入時にグローバルファイルキャッシュインスタンスを導入するために次のAPI要求を行います。

* CloudFormation：DescribeStack
* CloudWatch：GetMetricStatistics
* CloudFormation：リストスタック




=== Kubernetes

コネクタは、次のAPI要求を実行してAmazon EKSクラスタを検出および管理します。

* EC2: DescribeRegions (説明領域
* EKS：リストクラスタ
* EKS：DescribeCluster
* IAM：GetInstanceProfile

