---
sidebar: sidebar 
permalink: reference-permissions-gcp.html 
keywords: permissions, gcp, gcp permissions 
summary: Cloud Manager からクラウドプロバイダの処理を実行するには権限が必要です。これらの権限は、ネットアップが提供するポリシーに含まれています。このような権限を持つ Cloud Manager の機能を理解しておく必要があるかもしれません。 
---
= Connector の Google Cloud 権限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud ManagerでGoogle Cloudの処理を実行するには権限が必要です。これらの権限は、ネットアップが提供するカスタムロールに含まれています。このような権限を持つ Cloud Manager の機能を理解しておく必要があるかもしれません。



== サービスアカウントの権限

次のカスタムロールは、ConnectorがGoogle Cloudネットワーク内のリソースとプロセスを管理するために必要な権限を提供します。

このカスタムロールは、Connector VMに関連付けられているサービスアカウントに適用する必要があります。 link:task-creating-connectors-gcp.html["ステップバイステップの手順を確認します"]。

また、新しい権限が以降のリリースで追加されるときに、ロールが最新の状態であることを確認する必要があります。

[source, yaml]
----
title: NetApp Cloud Manager
description: Permissions for the service account associated with the Connector instance.
stage: GA
includedPermissions:
- iam.serviceAccounts.actAs
- compute.regionBackendServices.create
- compute.regionBackendServices.get
- compute.regionBackendServices.list
- compute.networks.updatePolicy
- compute.backendServices.create
- compute.addresses.list
- compute.disks.create
- compute.disks.createSnapshot
- compute.disks.delete
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.globalOperations.get
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.addAccessConfig
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.delete
- compute.instances.detachDisk
- compute.instances.get
- compute.instances.getSerialPortOutput
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.stop
- compute.instances.updateDisplayDevice
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.snapshots.create
- compute.snapshots.delete
- compute.snapshots.get
- compute.snapshots.list
- compute.snapshots.setLabels
- compute.subnetworks.get
- compute.subnetworks.list
- compute.subnetworks.use
- compute.subnetworks.useExternalIp
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- compute.instances.setServiceAccount
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- logging.logEntries.list
- logging.privateLogEntries.list
- resourcemanager.projects.get
- storage.buckets.create
- storage.buckets.delete
- storage.buckets.get
- storage.buckets.list
- cloudkms.cryptoKeyVersions.useToEncrypt
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.keyRings.list
- storage.buckets.update
- iam.serviceAccounts.getIamPolicy
- iam.serviceAccounts.list
- storage.objects.get
- storage.objects.list
- monitoring.timeSeries.list
- storage.buckets.getIamPolicy
----


== Google Cloud権限の使用方法

[cols="50,50"]
|===
| アクション | 目的 


| -compute.disks .create -computedisks .createsnapshot - compute.disks.delete -computedisks .get-compute.diskList - compute.disks.setLabels - compute.disks.us | Cloud Volumes ONTAP 用のディスクを作成および管理します。 


| -compute-firewalls .create - compute.firewalls.delete -comput領域 .firewalls .get-comput領域 .firewalls リスト | Cloud Volumes ONTAP のファイアウォールルールを作成します。 


| -computer.globalOperationsGet | 処理のステータスを確認できます。 


| -compute.image.get-compute.image.getFromFamily-compute.image.list - compute.images.useReadOnly | VM インスタンスのイメージを取得します。 


| - compute.instances.attachDisk - compute.instances.detachDisk | ディスクを Cloud Volumes ONTAP に接続して接続解除します。 


| - compute.instances.create - compute.instances.delete | Cloud Volumes ONTAP VM インスタンスを作成および削除します。 


| - compute.instances.get | VM インスタンスを一覧表示します。 


| - compute.instances.getSerialPortOutput | をクリックしてコンソールログを取得してください 


| - compute.instances.list | ゾーン内のインスタンスのリストを取得します。 


| - compute.instances.setDeletionProtection | インスタンスに削除保護を設定します。 


| - compute.instances.setLabels | ラベルを追加します。 


| - compute.instances.setMachineType - compute.instances.setMinCpuPlatform | Cloud Volumes ONTAP のマシンタイプを変更します。 


| - compute.instances.setMetadata | をクリックしてください。 


| - compute.instances.setTags | ファイアウォールルールのタグを追加します。 


| - compute.instances.start - compute.instances.stop - compute.instances.updateDisplayDevice | Cloud Volumes ONTAP を開始および停止します。 


| -computesCompute .machineTypes.get | コア数を取得して qoutas をチェックしてください。 


| - compute.projects.get | 複数のプロジェクトをサポートするため。 


| -compute-snapshots-create - compute.snapshots.delete -compute-snapshots-getCompute-snapshots-list - compute.snapshots.setLabels | 永続ディスクスナップショットを作成および管理するには、次の手順に従います。 


| - compute.networks.get - compute.networks.list - comput.regions.Get-comput領域 .list-comput領域 .subnetworks -compute.subnetworks .listCompute.zoneOperations-get-compute.zones .get-compute.zones リスト | 新しい Cloud Volumes ONTAP 仮想マシンインスタンスの作成に必要なネットワーク情報を取得するため。 


| - deploymentmanager.compositeTypes.get - deploymentmanager.compositeTypes.list - deploymentmanager.deployments.create - deploymentmanager.deployments.delete - deploymentmanager.deployments.get - deploymentmanager.deployments.list -deploymentmanager. マニフェスト .get-deploymentmanager. マニフェスト .list-list-deploymentmanager. operations-get-deploymentmanager. operationlist -deploymentmanager. resources.get-deploymentmanager. resources.list-deploymentmanager. typeProviders.get-deploymentmanager. typeProviders.list-deploymentmanager. -deploymentmanager. types] リスト | Google Cloud Deployment Manager を使用して Cloud Volumes ONTAP 仮想マシンインスタンスを導入します。 


| -logging.logEntries.list-logging.privateLogEntries.list | スタックログドライブを取得する方法 


| - resourcemanager.projects.get | 複数のプロジェクトをサポートするため。 


| -storagバケット 。 create - storage.buckets.delete -storagバケット .get-storagバケット .list-storagバケット .buckets-update | Google Cloud Storage バケットを作成して管理し、データを階層化します。 


| - cloudkms.cryptoKeyVersions.useToEncrypt - cloudkms .cryptoKeys.get-cloudkms .cryptoKeys.list-cloudkm.keyringlist.list | Cloud Volumes ONTAP でクラウドキー管理サービスからお客様が管理する暗号化キーを使用するため。 


| - compute.instances.setServiceAccount - iam.serviceAccounts.actAs - iam.serviceAccounts.getIamPolicy - iam.serviceAccounts.list - storage.objects-get -storage.objectlist | Cloud Volumes ONTAP インスタンスにサービスアカウントを設定します。このサービスアカウントは、 Google Cloud Storage バケットへのデータ階層化の権限を提供します。 


| -compute.address.listCompute.backendServices. create -compute.networks.updatePolicy -compute.regionBackendServices.create -compute.regionBackendServices.get -compute.regionBackendServices.list | をクリックしてください。 


| - compute.subnetworks.us e-compute.subnetworks.useExternalIp - compute.instances.addAccessConfig | クラウドデータの意味を有効にするため。 


| -container-type コンテナクラスタリスト | Google Kubernetes Engine で実行されている Kubernetes クラスタを検出する。 


| - compute.instanceGroups.get - compute .address.get | HAペアでStorage VMを作成および管理する。 


| -monitoring timeseries.list -storage.buckets-getIamPolicyを選択します | をクリックして、Google Cloud Storageバケットに関する情報を確認してください。 
|===